version: '2'
services:
  factorio:
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=2.0.43
        - SHA256=bde6e167330c4439ce7df3ac519ea445120258ef676f1f6ad31d0c2816d3aee3
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - UPDATE_MODS_ON_START=true
      #      - USERNAME=FactorioUsername
      #      - TOKEN=FactorioToken
      #      - PORT=34198
      #      - PRESET=deathworld
      #      - ADDR=::1
#    # Uncomment the following line to enable the use of the host's network stack,
#    # which may be necessary for some setups like NAS or when using some proxy service like firewall rules.
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
